export const getTicketsSuccessfulRes = {
  ok: true,
  status: 200,
  statusText: "OK",
  data: {
    tickets: [
      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/1.json",
        id: 1,
        external_id: null,
        via: {
          channel: "sample_ticket",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T20:26:25Z",
        updated_at: "2021-11-22T20:26:25Z",
        type: "incident",
        subject: "Sample ticket: Meet the ticket",
        raw_subject: "Sample ticket: Meet the ticket",
        description:
          "Hi there,\n\nI’m sending an email because I’m having a problem setting up your new product. Can you help me troubleshoot?\n\nThanks,\n The Customer\n\n",
        priority: "normal",
        status: "open",
        recipient: null,
        requester_id: 421913058332,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: null,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["sample", "support", "zendesk"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },

      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/11.json",
        id: 11,
        external_id: null,
        via: {
          channel: "api",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T21:25:39Z",
        updated_at: "2021-11-22T21:25:39Z",
        type: null,
        subject: "quis veniam ad sunt non",
        raw_subject: "quis veniam ad sunt non",
        description:
          "Magna culpa velit duis nisi sint veniam nisi adipisicing aute. Eiusmod id cupidatat pariatur tempor esse do. Aliquip ipsum voluptate eiusmod mollit. Et ullamco consectetur tempor cillum sunt anim enim cillum reprehenderit cillum proident. Eu aliqua excepteur eiusmod non ullamco aliqua esse laboris ad commodo reprehenderit pariatur consequat est.\n\nVoluptate eiusmod officia culpa nulla culpa mollit reprehenderit cillum adipisicing sit consectetur in. Anim occaecat excepteur commodo officia aute voluptate excepteur do ut esse occaecat duis consequat. Sunt minim est in non exercitation ad minim ullamco dolore in enim mollit aliquip. Ut ex dolore proident Lorem ut dolor ex. Laboris elit in in mollit. Quis id minim ex ad qui velit.",
        priority: null,
        status: "open",
        recipient: null,
        requester_id: 1903533515747,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: 361633406892,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["aliquip", "consequat", "magna"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },
      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/12.json",
        id: 12,
        external_id: null,
        via: {
          channel: "api",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T21:25:39Z",
        updated_at: "2021-11-22T21:25:39Z",
        type: null,
        subject: "tempor aliquip sint dolore incididunt",
        raw_subject: "tempor aliquip sint dolore incididunt",
        description:
          "Amet sint ea minim excepteur amet. Eiusmod duis ad ea ad aliquip occaecat ea voluptate sunt cillum duis aute. Esse in duis tempor et. Est duis nulla irure ullamco amet sit esse Lorem eu aliqua ullamco sunt. In sint dolore id eu ea.\n\nIrure proident nulla deserunt officia laboris culpa. Qui est adipisicing elit tempor cupidatat minim laborum ea est nostrud nulla mollit id dolore. Aute amet amet deserunt incididunt magna ipsum exercitation nostrud incididunt ea qui anim. Adipisicing irure commodo consectetur Lorem ad excepteur nulla eiusmod aliquip irure occaecat. Id sint fugiat proident Lorem est minim ea sint irure. Veniam sint ex minim duis est.",
        priority: null,
        status: "open",
        recipient: null,
        requester_id: 1903533515747,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: 361633406892,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["ad", "minim", "non"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },
      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/13.json",
        id: 13,
        external_id: null,
        via: {
          channel: "api",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T21:25:40Z",
        updated_at: "2021-11-22T21:25:40Z",
        type: null,
        subject: "labore pariatur ut laboris laboris",
        raw_subject: "labore pariatur ut laboris laboris",
        description:
          "Quis veniam consectetur ullamco aute incididunt eiusmod ut consectetur sunt laboris sint officia labore. Incididunt sit elit ipsum esse excepteur veniam Lorem excepteur amet amet tempor officia. Magna reprehenderit voluptate elit adipisicing consectetur laboris eu nisi ad excepteur adipisicing non duis proident.\n\nAliqua sunt ea dolor dolor elit occaecat. Aliqua reprehenderit commodo minim eu exercitation incididunt consectetur. Eiusmod anim ad adipisicing et ullamco id incididunt.",
        priority: null,
        status: "open",
        recipient: null,
        requester_id: 1903533515747,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: 361633406892,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["culpa", "dolor", "eiusmod"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },
      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/14.json",
        id: 14,
        external_id: null,
        via: {
          channel: "api",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T21:25:40Z",
        updated_at: "2021-11-22T21:25:40Z",
        type: null,
        subject: "officia mollit aliqua eu nostrud",
        raw_subject: "officia mollit aliqua eu nostrud",
        description:
          "Fugiat magna dolor ipsum dolor ex qui commodo deserunt veniam aliqua qui ex. Consequat est duis velit eu id labore id dolor sint laboris. Minim nisi sint aliquip nisi cillum magna deserunt non cupidatat est. Exercitation ea pariatur ipsum non pariatur dolor velit laboris dolore irure reprehenderit ut.\n\nAmet et officia eiusmod adipisicing. Amet ut ut tempor cillum aliqua elit mollit mollit. Exercitation commodo culpa adipisicing aute voluptate consectetur ut est ea quis aliquip duis excepteur. Anim quis quis occaecat fugiat occaecat. Non et deserunt anim eu anim non laborum ex tempor. Tempor aute reprehenderit minim consequat elit minim. Aliqua in laboris culpa excepteur qui enim excepteur cillum commodo eiusmod eu enim do ullamco.",
        priority: null,
        status: "open",
        recipient: null,
        requester_id: 1903533515747,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: 361633406892,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["cillum", "fugiat", "irure"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },

      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/22.json",
        id: 22,
        external_id: null,
        via: {
          channel: "api",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T21:25:44Z",
        updated_at: "2021-11-22T21:25:44Z",
        type: null,
        subject: "esse adipisicing consectetur sunt tempor",
        raw_subject: "esse adipisicing consectetur sunt tempor",
        description:
          "Anim occaecat nisi et velit fugiat tempor incididunt cillum nostrud ut sunt cupidatat ipsum. Tempor adipisicing elit consectetur culpa. Ad dolor velit consectetur tempor commodo est ipsum cillum incididunt esse ad ex velit. Proident eu esse eiusmod nulla mollit eu cupidatat consectetur consectetur exercitation reprehenderit laborum adipisicing do.\n\nLorem ad aliquip veniam nisi exercitation sit. Fugiat reprehenderit eu do officia commodo ea cillum et sunt laborum nostrud in. Dolore eu ad qui eu labore qui pariatur id. Et enim amet magna quis mollit qui. Esse laboris id voluptate do. Sunt mollit dolore proident fugiat minim mollit culpa esse minim sint ut consectetur occaecat. Incididunt culpa non nulla veniam ea laborum aliqua tempor nulla ea.",
        priority: null,
        status: "open",
        recipient: null,
        requester_id: 1903533515747,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: 361633406892,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["consectetur", "nulla", "occaecat"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },
      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/23.json",
        id: 23,
        external_id: null,
        via: {
          channel: "api",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T21:25:44Z",
        updated_at: "2021-11-22T21:25:44Z",
        type: null,
        subject: "sunt enim pariatur id id",
        raw_subject: "sunt enim pariatur id id",
        description:
          "Ut officia ut elit non velit nisi quis adipisicing consequat nostrud occaecat cillum. Do exercitation nulla officia consequat est velit eu id in et. Nulla culpa ullamco minim aliquip nisi ad ex. Qui aliquip ut esse ipsum magna do ipsum esse voluptate magna nisi sint ex. Laborum commodo culpa laboris quis incididunt. In enim dolore ad sunt aliquip nulla aliqua aute et amet ut veniam labore. Consectetur eiusmod et aliquip proident est Lorem proident nostrud esse eu consequat excepteur.\n\nExercitation duis labore irure deserunt reprehenderit do non. Incididunt dolore do nisi consectetur mollit anim in. Do dolor dolor amet enim et quis voluptate elit magna non laboris. Enim enim ea occaecat minim mollit velit id exercitation ea officia incididunt proident. Dolore fugiat esse Lorem amet consequat magna laborum fugiat. Id aliqua labore consequat laborum cillum fugiat incididunt non do ipsum.",
        priority: null,
        status: "open",
        recipient: null,
        requester_id: 1903533515747,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: 361633406892,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["eu", "pariatur", "tempor"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },
      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/24.json",
        id: 24,
        external_id: null,
        via: {
          channel: "api",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T21:25:45Z",
        updated_at: "2021-11-22T21:25:45Z",
        type: null,
        subject: "et ad ut enim labore",
        raw_subject: "et ad ut enim labore",
        description:
          "Consectetur dolore in minim anim reprehenderit do labore commodo officia ad ipsum amet quis ipsum. Amet ad dolor minim sint excepteur adipisicing exercitation elit. Non aliquip commodo voluptate sint veniam et ipsum magna occaecat do consequat incididunt magna do. Pariatur proident aliquip veniam dolore occaecat voluptate excepteur fugiat consequat in. Dolor ullamco ea cupidatat nostrud. Deserunt deserunt aliqua elit aute qui elit et in. Mollit cupidatat culpa officia ad qui deserunt tempor sint reprehenderit proident consectetur amet aliquip.\n\nAdipisicing sunt consequat labore ad ut elit anim minim esse Lorem non qui consequat. Dolore anim adipisicing ullamco nisi anim ipsum nulla magna proident nisi nulla ea. Ullamco duis nisi aliquip pariatur nulla ad occaecat.",
        priority: null,
        status: "open",
        recipient: null,
        requester_id: 1903533515747,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: 361633406892,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["aliqua", "dolor", "officia"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },
      {
        url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/25.json",
        id: 25,
        external_id: null,
        via: {
          channel: "api",
          source: {
            from: {},
            to: {},
            rel: null,
          },
        },
        created_at: "2021-11-22T21:25:45Z",
        updated_at: "2021-11-22T21:25:45Z",
        type: null,
        subject: "voluptate dolor deserunt ea deserunt",
        raw_subject: "voluptate dolor deserunt ea deserunt",
        description:
          "Consectetur eiusmod pariatur ullamco voluptate irure sunt magna cillum velit irure commodo culpa ipsum in. Nulla non exercitation dolor quis minim deserunt ad consequat officia ullamco irure consectetur anim mollit. Cupidatat exercitation cillum excepteur culpa consectetur ad adipisicing exercitation est amet ullamco id eiusmod tempor. Aliqua quis irure culpa tempor mollit veniam. Fugiat aliquip duis non sit id eu ea anim sit ea aliqua et dolor.\n\nCulpa culpa culpa id proident dolor magna ipsum dolor irure mollit proident culpa. Officia Lorem veniam dolor sit commodo id consequat ex qui enim veniam. Laboris velit excepteur sit sit anim nulla exercitation.",
        priority: null,
        status: "open",
        recipient: null,
        requester_id: 1903533515747,
        submitter_id: 1903533515747,
        assignee_id: 1903533515747,
        organization_id: 361633406892,
        group_id: 360022304392,
        collaborator_ids: [],
        follower_ids: [],
        email_cc_ids: [],
        forum_topic_id: null,
        problem_id: null,
        has_incidents: false,
        is_public: true,
        due_at: null,
        tags: ["do", "est", "labore"],
        custom_fields: [],
        satisfaction_rating: null,
        sharing_agreement_ids: [],
        followup_ids: [],
        ticket_form_id: 360003512572,
        brand_id: 360007066612,
        allow_channelback: false,
        allow_attachments: true,
      },
    ],
    meta: {
      has_more: true,
      after_cursor: "eyJvIjoibmljZV9pZCIsInYiOiJhUmtBQUFBQUFBQUEifQ==",
      before_cursor: "eyJvIjoibmljZV9pZCIsInYiOiJhUUVBQUFBQUFBQUEifQ==",
    },
    links: {
      prev: "https://zcczendeskcc.zendesk.com/api/v2/tickets.json?page%5Bbefore%5D=eyJvIjoibmljZV9pZCIsInYiOiJhUUVBQUFBQUFBQUEifQ%3D%3D&page%5Bsize%5D=25",
      next: "https://zcczendeskcc.zendesk.com/api/v2/tickets.json?page%5Bafter%5D=eyJvIjoibmljZV9pZCIsInYiOiJhUmtBQUFBQUFBQUEifQ%3D%3D&page%5Bsize%5D=25",
    },
  },
};

export const getTicketsUnSuccessfulRes = {
  status: 401,
  statusText: "Unauthorised: ",
  data: null,
  ok: false,
};
export const getTicketsUnSuccessfulRes2 = {
  status: 404,
  statusText: "Not found: ",
  data: null,
  ok: false,
};

export const getTicketsUnSuccessfulRes3 = {
  status: 429,
  statusText: "Usage limit Exceeded, please contact support.",
  data: null,
  ok: false,
};

export const getTicketsUnSuccessfulRes4 = {
  status: 400,
  statusText: "Request not successful",
  data: null,
  ok: false,
};

export const getTicketsUnSuccessfulRes5 = {
  status: 500,
  statusText: "Server error",
  data: null,
  ok: false,
};

export const getTicketSuccessfulRes = {
  ok: true,
  status: 200,
  statusText: "OK",
  data: {
    ticket: {
      url: "https://zcczendeskcc.zendesk.com/api/v2/tickets/1.json",
      id: 1,
      external_id: null,
      via: {
        channel: "sample_ticket",
        source: {
          from: {},
          to: {},
          rel: null,
        },
      },
      created_at: "2021-11-22T20:26:25Z",
      updated_at: "2021-11-22T20:26:25Z",
      type: "incident",
      subject: "Sample ticket: Meet the ticket",
      raw_subject: "Sample ticket: Meet the ticket",
      description:
        "Hi there,\n\nI’m sending an email because I’m having a problem setting up your new product. Can you help me troubleshoot?\n\nThanks,\n The Customer\n\n",
      priority: "normal",
      status: "open",
      recipient: null,
      requester_id: 421913058332,
      submitter_id: 1903533515747,
      assignee_id: 1903533515747,
      organization_id: null,
      group_id: 360022304392,
      collaborator_ids: [],
      follower_ids: [],
      email_cc_ids: [],
      forum_topic_id: null,
      problem_id: null,
      has_incidents: false,
      is_public: true,
      due_at: null,
      tags: ["sample", "support", "zendesk"],
      custom_fields: [],
      satisfaction_rating: null,
      sharing_agreement_ids: [],
      followup_ids: [],
      ticket_form_id: 360003512572,
      brand_id: 360007066612,
      allow_channelback: false,
      allow_attachments: true,
    },
  },
};

export const getTicketUnSuccessfulRes = {
  status: 404,
  statusText: "Ticket not found: ",
  data: null,
  ok: false,
};

export const getTicketUnSuccessfulRes2 = {
  status: 401,
  statusText: "Couldn't authenticate you: ",
  data: null,
  ok: false,
};

export const getTicketUnSuccessfulRes3 = {
  status: 400,
  statusText: "Invalid Ticket Id: ",
  data: null,
  ok: false,
};

export const getTicketUnSuccessfulRes4 = {
  status: 500,
  statusText: "Server error",
  data: null,
  ok: false,
};
